# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Alumno(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, dni: str=None, fecha_limite: str=None, tramo: str=None, pagado: bool=None):
        """
        Alumno - a model defined in Swagger

        :param dni: The dni of this Alumno.
        :type dni: str
        :param fecha_limite: The fecha_limite of this Alumno.
        :type fecha_limite: str
        :param tramo: The tramo of this Alumno.
        :type tramo: str
        :param pagado: The pagado of this Alumno.
        :type pagado: bool
        """
        self.swagger_types = {
            'dni': str,
            'fecha_limite': str,
            'tramo': str,
            'pagado': bool
        }

        self.attribute_map = {
            'dni': 'dni',
            'fecha_limite': 'fecha_limite',
            'tramo': 'tramo',
            'pagado': 'pagado'
        }

        self._dni = dni
        self._fecha_limite = fecha_limite
        self._tramo = tramo
        self._pagado = pagado

    @classmethod
    def from_dict(cls, dikt) -> 'Alumno':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Alumno of this Alumno.
        :rtype: Alumno
        """
        return deserialize_model(dikt, cls)

    @property
    def dni(self) -> str:
        """
        Gets the dni of this Alumno.

        :return: The dni of this Alumno.
        :rtype: str
        """
        return self._dni

    @dni.setter
    def dni(self, dni: str):
        """
        Sets the dni of this Alumno.

        :param dni: The dni of this Alumno.
        :type dni: str
        """

        self._dni = dni

    @property
    def fecha_limite(self) -> str:
        """
        Gets the fecha_limite of this Alumno.

        :return: The fecha_limite of this Alumno.
        :rtype: str
        """
        return self._fecha_limite

    @fecha_limite.setter
    def fecha_limite(self, fecha_limite: str):
        """
        Sets the fecha_limite of this Alumno.

        :param fecha_limite: The fecha_limite of this Alumno.
        :type fecha_limite: str
        """

        self._fecha_limite = fecha_limite

    @property
    def tramo(self) -> str:
        """
        Gets the tramo of this Alumno.

        :return: The tramo of this Alumno.
        :rtype: str
        """
        return self._tramo

    @tramo.setter
    def tramo(self, tramo: str):
        """
        Sets the tramo of this Alumno.

        :param tramo: The tramo of this Alumno.
        :type tramo: str
        """

        self._tramo = tramo

    @property
    def pagado(self) -> bool:
        """
        Gets the pagado of this Alumno.

        :return: The pagado of this Alumno.
        :rtype: bool
        """
        return self._pagado

    @pagado.setter
    def pagado(self, pagado: bool):
        """
        Sets the pagado of this Alumno.

        :param pagado: The pagado of this Alumno.
        :type pagado: bool
        """

        self._pagado = pagado

