# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Espacio(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, cod_id: int=None, fecha: str=None, hora: str=None, id_prof: int=None, cantidad: float=None):
        """
        Espacio - a model defined in Swagger

        :param cod_id: The cod_id of this Espacio.
        :type cod_id: int
        :param fecha: The fecha of this Espacio.
        :type fecha: str
        :param hora: The hora of this Espacio.
        :type hora: str
        :param id_prof: The id_prof of this Espacio.
        :type id_prof: int
        :param cantidad: The cantidad of this Espacio.
        :type cantidad: float
        """
        self.swagger_types = {
            'cod_id': int,
            'fecha': str,
            'hora': str,
            'id_prof': int,
            'cantidad': float
        }

        self.attribute_map = {
            'cod_id': 'cod_id',
            'fecha': 'fecha',
            'hora': 'hora',
            'id_prof': 'id_prof',
            'cantidad': 'cantidad'
        }

        self._cod_id = cod_id
        self._fecha = fecha
        self._hora = hora
        self._id_prof = id_prof
        self._cantidad = cantidad

    @classmethod
    def from_dict(cls, dikt) -> 'Espacio':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Espacio of this Espacio.
        :rtype: Espacio
        """
        return deserialize_model(dikt, cls)

    @property
    def cod_id(self) -> int:
        """
        Gets the cod_id of this Espacio.

        :return: The cod_id of this Espacio.
        :rtype: int
        """
        return self._cod_id

    @cod_id.setter
    def cod_id(self, cod_id: int):
        """
        Sets the cod_id of this Espacio.

        :param cod_id: The cod_id of this Espacio.
        :type cod_id: int
        """

        self._cod_id = cod_id

    @property
    def fecha(self) -> str:
        """
        Gets the fecha of this Espacio.

        :return: The fecha of this Espacio.
        :rtype: str
        """
        return self._fecha

    @fecha.setter
    def fecha(self, fecha: str):
        """
        Sets the fecha of this Espacio.

        :param fecha: The fecha of this Espacio.
        :type fecha: str
        """

        self._fecha = fecha

    @property
    def hora(self) -> str:
        """
        Gets the hora of this Espacio.

        :return: The hora of this Espacio.
        :rtype: str
        """
        return self._hora

    @hora.setter
    def hora(self, hora: str):
        """
        Sets the hora of this Espacio.

        :param hora: The hora of this Espacio.
        :type hora: str
        """

        self._hora = hora

    @property
    def id_prof(self) -> int:
        """
        Gets the id_prof of this Espacio.

        :return: The id_prof of this Espacio.
        :rtype: int
        """
        return self._id_prof

    @id_prof.setter
    def id_prof(self, id_prof: int):
        """
        Sets the id_prof of this Espacio.

        :param id_prof: The id_prof of this Espacio.
        :type id_prof: int
        """

        self._id_prof = id_prof

    @property
    def cantidad(self) -> float:
        """
        Gets the cantidad of this Espacio.

        :return: The cantidad of this Espacio.
        :rtype: float
        """
        return self._cantidad

    @cantidad.setter
    def cantidad(self, cantidad: float):
        """
        Sets the cantidad of this Espacio.

        :param cantidad: The cantidad of this Espacio.
        :type cantidad: float
        """

        self._cantidad = cantidad

