swagger: '2.0'
info:
  description: API para la consulta de pagos
  version: 1.0.0
  title: API Pagos
host: 'localhost:8080'
basePath: /apiPagos
tags:
  - name: Alumnos
    description: operaciones sobre alumnos
  - name: Profesor
    description: operaciones sobre los profesores
  - name: Espacio
    description: operaciones sobre los espacios
schemes:
  - https
paths:
  '/alumno/{dni}':
    get:
      tags:
        - Alumnos
      summary: Consulta el pago del alumno
      description: Nos indica si el alumno ha pagado
      operationId: pago_alumno
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: dni
          in: path
          required: true
          description: El dni del alumno
          type: string
      responses:
        '200':
          description: Consulta realizada
          schema:
            type: string
            items:
              $ref: '#/definitions/Alumno'
        '404':
          description: Error en consulta
      x-swagger-router-controller: swagger_server.controllers.alumnos_controller
  '/profesor/{dni}':
    get:
      tags:
        - Profesor
      summary: Consulta pago nomina
      description: Indica si el profesor ha cobrado su nomina
      operationId: cobro_nomina
      produces:
        - application/xml
        - application/json
      parameters:
        - name: dni
          in: path
          required: true
          description: El dni del profesor
          type: string
      responses:
        '200':
          description: Consulta realizada
          schema:
            type: string
            items:
              $ref: '#/definitions/Profesor'
        '404':
          description: Error en consulta
      x-swagger-router-controller: swagger_server.controllers.profesor_controller
  '/espacio/{id_espacio}':
    get:
      tags:
        - Espacio
      summary: Consulta pago/alquiler espacio.
      description: Indica si el espacio ha sido pagado
      operationId: pago_espacio
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: id_espacio
          in: path
          required: true
          description: El identificador del espacio
          type: integer
      responses:
        '200':
          description: Consulta realizada
          schema:
            $ref: '#/definitions/Espacio'
        '404':
          description: Error en cosulta
      x-swagger-router-controller: swagger_server.controllers.espacio_controller
definitions:
  Profesor:
    type: object
    properties:
      dni:
        type: string
  Espacio:
    type: object
    properties:
      id_espacio:
        type: integer
  Alumno:
    type: object
    properties:
      dni:
        type: string
