# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Alumno(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, dni: str=None, nombre: str=None, ape1: str=None, ape2: str=None, fecha: str=None, correo: str=None, grado: str=None):
        """
        Alumno - a model defined in Swagger

        :param dni: The dni of this Alumno.
        :type dni: str
        :param nombre: The nombre of this Alumno.
        :type nombre: str
        :param ape1: The ape1 of this Alumno.
        :type ape1: str
        :param ape2: The ape2 of this Alumno.
        :type ape2: str
        :param fecha: The fecha of this Alumno.
        :type fecha: str
        :param correo: The correo of this Alumno.
        :type correo: str
        :param grado: The grado of this Alumno.
        :type grado: str
        """
        self.swagger_types = {
            'dni': str,
            'nombre': str,
            'ape1': str,
            'ape2': str,
            'fecha': str,
            'correo': str,
            'grado': str
        }

        self.attribute_map = {
            'dni': 'dni',
            'nombre': 'nombre',
            'ape1': 'ape1',
            'ape2': 'ape2',
            'fecha': 'fecha',
            'correo': 'correo',
            'grado': 'grado'
        }

        self._dni = dni
        self._nombre = nombre
        self._ape1 = ape1
        self._ape2 = ape2
        self._fecha = fecha
        self._correo = correo
        self._grado = grado

    @classmethod
    def from_dict(cls, dikt) -> 'Alumno':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Alumno of this Alumno.
        :rtype: Alumno
        """
        return deserialize_model(dikt, cls)

    @property
    def dni(self) -> str:
        """
        Gets the dni of this Alumno.

        :return: The dni of this Alumno.
        :rtype: str
        """
        return self._dni

    @dni.setter
    def dni(self, dni: str):
        """
        Sets the dni of this Alumno.

        :param dni: The dni of this Alumno.
        :type dni: str
        """

        self._dni = dni

    @property
    def nombre(self) -> str:
        """
        Gets the nombre of this Alumno.

        :return: The nombre of this Alumno.
        :rtype: str
        """
        return self._nombre

    @nombre.setter
    def nombre(self, nombre: str):
        """
        Sets the nombre of this Alumno.

        :param nombre: The nombre of this Alumno.
        :type nombre: str
        """

        self._nombre = nombre

    @property
    def ape1(self) -> str:
        """
        Gets the ape1 of this Alumno.

        :return: The ape1 of this Alumno.
        :rtype: str
        """
        return self._ape1

    @ape1.setter
    def ape1(self, ape1: str):
        """
        Sets the ape1 of this Alumno.

        :param ape1: The ape1 of this Alumno.
        :type ape1: str
        """

        self._ape1 = ape1

    @property
    def ape2(self) -> str:
        """
        Gets the ape2 of this Alumno.

        :return: The ape2 of this Alumno.
        :rtype: str
        """
        return self._ape2

    @ape2.setter
    def ape2(self, ape2: str):
        """
        Sets the ape2 of this Alumno.

        :param ape2: The ape2 of this Alumno.
        :type ape2: str
        """

        self._ape2 = ape2

    @property
    def fecha(self) -> str:
        """
        Gets the fecha of this Alumno.

        :return: The fecha of this Alumno.
        :rtype: str
        """
        return self._fecha

    @fecha.setter
    def fecha(self, fecha: str):
        """
        Sets the fecha of this Alumno.

        :param fecha: The fecha of this Alumno.
        :type fecha: str
        """

        self._fecha = fecha

    @property
    def correo(self) -> str:
        """
        Gets the correo of this Alumno.

        :return: The correo of this Alumno.
        :rtype: str
        """
        return self._correo

    @correo.setter
    def correo(self, correo: str):
        """
        Sets the correo of this Alumno.

        :param correo: The correo of this Alumno.
        :type correo: str
        """

        self._correo = correo

    @property
    def grado(self) -> str:
        """
        Gets the grado of this Alumno.

        :return: The grado of this Alumno.
        :rtype: str
        """
        return self._grado

    @grado.setter
    def grado(self, grado: str):
        """
        Sets the grado of this Alumno.

        :param grado: The grado of this Alumno.
        :type grado: str
        """

        self._grado = grado

