# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Matricula(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id_alumno: int=None, asignaturas: List[int]=None, plazo: str=None):
        """
        Matricula - a model defined in Swagger

        :param id_alumno: The id_alumno of this Matricula.
        :type id_alumno: int
        :param asignaturas: The asignaturas of this Matricula.
        :type asignaturas: List[int]
        :param plazo: The plazo of this Matricula.
        :type plazo: str
        """
        self.swagger_types = {
            'id_alumno': int,
            'asignaturas': List[int],
            'plazo': str
        }

        self.attribute_map = {
            'id_alumno': 'idAlumno',
            'asignaturas': 'asignaturas',
            'plazo': 'plazo'
        }

        self._id_alumno = id_alumno
        self._asignaturas = asignaturas
        self._plazo = plazo

    @classmethod
    def from_dict(cls, dikt) -> 'Matricula':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Matricula of this Matricula.
        :rtype: Matricula
        """
        return deserialize_model(dikt, cls)

    @property
    def id_alumno(self) -> int:
        """
        Gets the id_alumno of this Matricula.

        :return: The id_alumno of this Matricula.
        :rtype: int
        """
        return self._id_alumno

    @id_alumno.setter
    def id_alumno(self, id_alumno: int):
        """
        Sets the id_alumno of this Matricula.

        :param id_alumno: The id_alumno of this Matricula.
        :type id_alumno: int
        """

        self._id_alumno = id_alumno

    @property
    def asignaturas(self) -> List[int]:
        """
        Gets the asignaturas of this Matricula.

        :return: The asignaturas of this Matricula.
        :rtype: List[int]
        """
        return self._asignaturas

    @asignaturas.setter
    def asignaturas(self, asignaturas: List[int]):
        """
        Sets the asignaturas of this Matricula.

        :param asignaturas: The asignaturas of this Matricula.
        :type asignaturas: List[int]
        """

        self._asignaturas = asignaturas

    @property
    def plazo(self) -> str:
        """
        Gets the plazo of this Matricula.

        :return: The plazo of this Matricula.
        :rtype: str
        """
        return self._plazo

    @plazo.setter
    def plazo(self, plazo: str):
        """
        Sets the plazo of this Matricula.

        :param plazo: The plazo of this Matricula.
        :type plazo: str
        """
        allowed_values = ["uno", "dos", "tres"]
        if plazo not in allowed_values:
            raise ValueError(
                "Invalid value for `plazo` ({0}), must be one of {1}"
                .format(plazo, allowed_values)
            )

        self._plazo = plazo

