# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Alumno(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, dni: str=None, nombre: str=None, id_asignatura: int=None, nombre_asignatura: str=None):
        """
        Alumno - a model defined in Swagger

        :param dni: The dni of this Alumno.
        :type dni: str
        :param nombre: The nombre of this Alumno.
        :type nombre: str
        :param id_asignatura: The id_asignatura of this Alumno.
        :type id_asignatura: int
        :param nombre_asignatura: The nombre_asignatura of this Alumno.
        :type nombre_asignatura: str
        """
        self.swagger_types = {
            'dni': str,
            'nombre': str,
            'id_asignatura': int,
            'nombre_asignatura': str
        }

        self.attribute_map = {
            'dni': 'dni',
            'nombre': 'nombre',
            'id_asignatura': 'id_asignatura',
            'nombre_asignatura': 'nombreAsignatura'
        }

        self._dni = dni
        self._nombre = nombre
        self._id_asignatura = id_asignatura
        self._nombre_asignatura = nombre_asignatura

    @classmethod
    def from_dict(cls, dikt) -> 'Alumno':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Alumno of this Alumno.
        :rtype: Alumno
        """
        return deserialize_model(dikt, cls)

    @property
    def dni(self) -> str:
        """
        Gets the dni of this Alumno.

        :return: The dni of this Alumno.
        :rtype: str
        """
        return self._dni

    @dni.setter
    def dni(self, dni: str):
        """
        Sets the dni of this Alumno.

        :param dni: The dni of this Alumno.
        :type dni: str
        """

        self._dni = dni

    @property
    def nombre(self) -> str:
        """
        Gets the nombre of this Alumno.

        :return: The nombre of this Alumno.
        :rtype: str
        """
        return self._nombre

    @nombre.setter
    def nombre(self, nombre: str):
        """
        Sets the nombre of this Alumno.

        :param nombre: The nombre of this Alumno.
        :type nombre: str
        """

        self._nombre = nombre

    @property
    def id_asignatura(self) -> int:
        """
        Gets the id_asignatura of this Alumno.

        :return: The id_asignatura of this Alumno.
        :rtype: int
        """
        return self._id_asignatura

    @id_asignatura.setter
    def id_asignatura(self, id_asignatura: int):
        """
        Sets the id_asignatura of this Alumno.

        :param id_asignatura: The id_asignatura of this Alumno.
        :type id_asignatura: int
        """

        self._id_asignatura = id_asignatura

    @property
    def nombre_asignatura(self) -> str:
        """
        Gets the nombre_asignatura of this Alumno.

        :return: The nombre_asignatura of this Alumno.
        :rtype: str
        """
        return self._nombre_asignatura

    @nombre_asignatura.setter
    def nombre_asignatura(self, nombre_asignatura: str):
        """
        Sets the nombre_asignatura of this Alumno.

        :param nombre_asignatura: The nombre_asignatura of this Alumno.
        :type nombre_asignatura: str
        """

        self._nombre_asignatura = nombre_asignatura

