# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Asignatura(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id_asignatura: int=None, id_departamento: int=None, nombre: str=None):
        """
        Asignatura - a model defined in Swagger

        :param id_asignatura: The id_asignatura of this Asignatura.
        :type id_asignatura: int
        :param id_departamento: The id_departamento of this Asignatura.
        :type id_departamento: int
        :param nombre: The nombre of this Asignatura.
        :type nombre: str
        """
        self.swagger_types = {
            'id_asignatura': int,
            'id_departamento': int,
            'nombre': str
        }

        self.attribute_map = {
            'id_asignatura': 'id_asignatura',
            'id_departamento': 'id_departamento',
            'nombre': 'nombre'
        }

        self._id_asignatura = id_asignatura
        self._id_departamento = id_departamento
        self._nombre = nombre

    @classmethod
    def from_dict(cls, dikt) -> 'Asignatura':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Asignatura of this Asignatura.
        :rtype: Asignatura
        """
        return deserialize_model(dikt, cls)

    @property
    def id_asignatura(self) -> int:
        """
        Gets the id_asignatura of this Asignatura.

        :return: The id_asignatura of this Asignatura.
        :rtype: int
        """
        return self._id_asignatura

    @id_asignatura.setter
    def id_asignatura(self, id_asignatura: int):
        """
        Sets the id_asignatura of this Asignatura.

        :param id_asignatura: The id_asignatura of this Asignatura.
        :type id_asignatura: int
        """

        self._id_asignatura = id_asignatura

    @property
    def id_departamento(self) -> int:
        """
        Gets the id_departamento of this Asignatura.

        :return: The id_departamento of this Asignatura.
        :rtype: int
        """
        return self._id_departamento

    @id_departamento.setter
    def id_departamento(self, id_departamento: int):
        """
        Sets the id_departamento of this Asignatura.

        :param id_departamento: The id_departamento of this Asignatura.
        :type id_departamento: int
        """

        self._id_departamento = id_departamento

    @property
    def nombre(self) -> str:
        """
        Gets the nombre of this Asignatura.

        :return: The nombre of this Asignatura.
        :rtype: str
        """
        return self._nombre

    @nombre.setter
    def nombre(self, nombre: str):
        """
        Sets the nombre of this Asignatura.

        :param nombre: The nombre of this Asignatura.
        :type nombre: str
        """

        self._nombre = nombre

