swagger: '2.0'
info:
  description: API para la gestión de los alumnos de la Universidad
  version: 1.0.0
  title: API Alumno
host: 'localhost:8080'
basePath: /apiAlumno
tags:
  - name: Alumnos
    description: operaciones sobre alumnos
  - name: Asignaturas
    description: operaciones sobre las asignaturas
  - name: Carreras
    description: operaciones sobre las carreras
schemes:
  - https
paths:
  /alumnos:
    get:
      tags:
        - Alumnos
      summary: Obtiene los alumnos
      description: Obtiene un listado de alumnos del sistema.
      operationId: obtener_alumnos
      produces:
        - application/xml
        - application/json
      parameters:
        - name: tamanoPagina
          in: query
          description: Número de alumnos devueltas
          required: false
          type: integer
        - name: numeroPaginas
          in: query
          description: Número de páginas devueltas
          required: false
          type: integer
      responses:
        '200':
          description: Una lista de alumnos
          schema:
            type: array
            items:
              $ref: '#/definitions/Alumno'
      x-swagger-router-controller: swagger_server.controllers.alumnos_controller
  /alumno:
    post:
      tags:
        - Alumnos
      summary: Crea un alumno
      description: Añade un alumno a la lista.
      operationId: crear_alumno
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: alumno
          description: El alumno que se va a añadir.
          required: true
          schema:
            $ref: '#/definitions/Alumno'
      responses:
        '200':
          description: Alumno creado correctamente.
        '400':
          description: El alumno no ha podido ser creado.
      x-swagger-router-controller: swagger_server.controllers.alumnos_controller
  '/alumno/{dni}':
    get:
      tags:
        - Alumnos
      summary: Devuelve expediente alumno.
      description: Devuelve el expediente de alumno utilizando el dni.
      operationId: get_alumno
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: dni
          in: path
          required: true
          description: El dni del alumno
          type: string
      responses:
        '200':
          description: Datos expediente alumno.
          schema:
            $ref: '#/definitions/Alumno'
        '404':
          description: El Alumno no existe.
      x-swagger-router-controller: swagger_server.controllers.alumnos_controller
    delete:
      tags:
        - Alumnos
      summary: elimina un alumno
      description: elimina un alumno de la lista
      operationId: borrar_alumno
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: dni
          in: path
          required: true
          description: dni del alumno a eliminar
          type: string
      responses:
        '204':
          description: Alumno eliminado.
        '400':
          description: No se pudo eliminar el alumno.
      x-swagger-router-controller: swagger_server.controllers.alumnos_controller
  /alumno/carrera:
    get:
      tags:
        - Alumnos
      summary: Alumnos de una carrera.
      description: Devuelve los alumnos de una carrera.
      operationId: get_alumnos_por_carrera
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: carrera
          in: query
          required: true
          description: La carrera de la Universidad
          type: string
          enum:
            - Ingenieria informatica
            - Ingenieria de telecomunicaciones
            - Ingenieria industrial
      responses:
        '200':
          description: Una lista de alumnos
          schema:
            type: array
            items:
              $ref: '#/definitions/Alumno'
        '404':
          description: No hay alumnos matriculados en esa carrera.
      x-swagger-router-controller: swagger_server.controllers.alumnos_controller
  /alumnos/asignatura:
    get:
      tags:
        - Alumnos
      summary: Alumnos de una asignatura.
      description: Devuelve los alumnos de una asignatura.
      operationId: get_alumnos_por_asignatura
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: asignatura
          in: query
          required: true
          description: La asignatura de la Universidad
          type: string
      responses:
        '200':
          description: Una lista de alumnos
          schema:
            type: array
            items:
              $ref: '#/definitions/Alumno'
        '404':
          description: No hay alumnos matriculados en esa asignatura.
      x-swagger-router-controller: swagger_server.controllers.alumnos_controller
  /asignaturas:
    get:
      tags:
        - Asignaturas
      summary: Obtiene las asignaturas
      description: Obtiene un listado de las asignaturas de la universidad.
      operationId: obtener_asignaturas
      produces:
        - application/xml
        - application/json
      parameters:
        - name: tamanoPagina
          in: query
          description: Número de asignaturas devueltas
          required: false
          type: integer
        - name: numeroPaginas
          in: query
          description: Número de páginas devueltas
          required: false
          type: integer
      responses:
        '200':
          description: Una lista de asignaturas
          schema:
            type: array
            items:
              $ref: '#/definitions/Asignatura'
      x-swagger-router-controller: swagger_server.controllers.asignaturas_controller
  '/asignaturas/{nombre}':
    get:
      tags:
        - Asignaturas
      summary: Devuelve una asignatura.
      description: Devuelve una asignatura por su nombre.
      operationId: get_asignatura
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - name: nombre
          in: path
          required: true
          description: El nombre de la asignatura
          type: string
      responses:
        '200':
          description: Una Asignatura
          schema:
            $ref: '#/definitions/Asignatura'
        '404':
          description: La Asignatura no existe.
      x-swagger-router-controller: swagger_server.controllers.asignaturas_controller
  /carrera:
    get:
      tags:
        - Carreras
      summary: Devuelve todas las carreras
      description: Devuelve todas las carreras de la Universidad
      operationId: get_carreras
      consumes:
        - application/xml
        - application/json
      produces:
        - application/xml
        - application/json
      responses:
        '200':
          description: Las carreras de la Universidad.
          schema:
            type: array
            items:
              $ref: '#/definitions/Carrera'
        '400':
          description: No hay carreras dadas de alta.
    x-swagger-router-controller: swagger_server.controllers.carreras_controller
  '/carrera/{nombre}':
    get:
      tags:
        - Carreras
      summary: Devuelve asignaturas pertenecientes a la carrera
      description: Devuelve asignaturas de la carrera pasada por parametro
      operationId: get_asignaturas_carrera
      consumes:
        - application/xml
        - application/json
      produces:
        - application/xml
        - application/json
      parameters:
        - name: nombre
          in: path
          required: true
          description: El nombre de la carrera
          type: string
      responses:
        '200':
          description: Lista asignaturas de la carrera.
          schema:
            type: array
            items:
              $ref: '#/definitions/Asignatura'
        '400':
          description: No hay carreras con ese nombre.
    x-swagger-router-controller: swagger_server.controllers.carreras_controller
definitions:
  Carrera:
    type: object
    properties:
      codigo:
        type: integer
      nombre:
        type: string
      credTransversales:
        type: integer
      credObligatorios:
        type: integer
      credOptativos:
        type: integer
      credTotales:
        type: integer
  Asignatura:
    type: object
    properties:
      codigo:
        type: integer
      nombre:
        type: string
      tipo:
        type: string
        enum:
          - Transversal
          - Optativa
          - Obligatoria
      creditos:
        type: integer
      curso:
        type: integer
  Alumno:
    type: object
    properties:
      dni:
        type: string
      nombre:
        type: string
      ape1:
        type: string
      ape2:
        type: string
      fecha:
        type: string
      correo:
        type: string
      grado:
        type: string
      asignaturas:
        type: array
        items:
          $ref: '#/definitions/Alumno'
      credObligatorios:
        type: integer
      credTransversales:
        type: integer
      credOptativos:
        type: integer
