# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Matricula(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id_alumno: int=None, asignaturas: List[str]=None):
        """
        Matricula - a model defined in Swagger

        :param id_alumno: The id_alumno of this Matricula.
        :type id_alumno: int
        :param asignaturas: The asignaturas of this Matricula.
        :type asignaturas: List[str]
        """
        self.swagger_types = {
            'id_alumno': int,
            'asignaturas': List[str]
        }

        self.attribute_map = {
            'id_alumno': 'idAlumno',
            'asignaturas': 'asignaturas'
        }

        self._id_alumno = id_alumno
        self._asignaturas = asignaturas

    @classmethod
    def from_dict(cls, dikt) -> 'Matricula':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Matricula of this Matricula.
        :rtype: Matricula
        """
        return deserialize_model(dikt, cls)

    @property
    def id_alumno(self) -> int:
        """
        Gets the id_alumno of this Matricula.

        :return: The id_alumno of this Matricula.
        :rtype: int
        """
        return self._id_alumno

    @id_alumno.setter
    def id_alumno(self, id_alumno: int):
        """
        Sets the id_alumno of this Matricula.

        :param id_alumno: The id_alumno of this Matricula.
        :type id_alumno: int
        """

        self._id_alumno = id_alumno

    @property
    def asignaturas(self) -> List[str]:
        """
        Gets the asignaturas of this Matricula.

        :return: The asignaturas of this Matricula.
        :rtype: List[str]
        """
        return self._asignaturas

    @asignaturas.setter
    def asignaturas(self, asignaturas: List[str]):
        """
        Sets the asignaturas of this Matricula.

        :param asignaturas: The asignaturas of this Matricula.
        :type asignaturas: List[str]
        """

        self._asignaturas = asignaturas

